fix fmin for stellar BBH
ConWea/connor-BBHX-waveform-model pull request #2
Opened 2022-10-24 12:40 UTC by WuShichao

2022-10-25 09:05 UTC, spxiwh commented on BBHX_PhenomD.py
> +    wave_gen = get_waveform_genner(mf_min=f_min*MTSUN_SI*(m1+m2), run_phenomd=run_phenomd)
I note that in this case mf_min will always have different values, and therefore we should *not* use lru_cache because it won't be able to do anything. Maybe we could lock mf_min to nearest order of magnitude (or half order-of-magnitude), but it might be easy to just ignore this and remove the caching of the waveform_generator

2022-10-25 09:06 UTC, spxiwh commented on BBHX_PhenomD.py
> +        err_msg = f"Must provide 'f_lower' or 't_obs_start'."
I think you get this message also if you provide *both*

2022-10-25 09:08 UTC, spxiwh commented on BBHX_PhenomD.py
> +        f_min = tf_track(t_obs_start) # in Hz
How slow is this compared to waveform generation? We want any call to this function to be dominated by calling BBHx. Is that still the case with an interp1d here?

2022-10-25 09:09 UTC, spxiwh commented on BBHX_PhenomD.py
> +@functools.lru_cache()
Shouldn't be cached assuming m1/m2 are different every time.

2022-10-25 09:32 UTC, WuShichao commented on BBHX_PhenomD.py
> +@functools.lru_cache()
@spxiwh According to this example https://docs.python.org/3/library/functools.html it seems it can receive a variable. If not, are there any other methods to accelerate?

2022-10-25 09:37 UTC, WuShichao commented on BBHX_PhenomD.py
> +        f_min = tf_track(t_obs_start) # in Hz
In my first implementation, I used the `phenomhm.tf` from BBHx to calculate the T-F track https://github.com/ConWea/BBHX-waveform-model/pull/2/commits/b0f37f264b6b76c99fa40879350f07a31534b898#diff-e1cfc5e431679fd715906b0736189454cd43ababe331a5c6def3cb416e040b50R42, but Alex said we shouldn't generate entire waveform to get it, so I use the PN equation for chirp time from PyCBC https://github.com/gwastro/pycbc/blob/master/pycbc/waveform/spa_tmplt.py#L32 I think it's faster.

2022-10-25 09:47 UTC, WuShichao commented on BBHX_PhenomD.py
> +        err_msg = f"Must provide 'f_lower' or 't_obs_start'."
Yes, I have noticed that, in that case, I think we should force users just set one of them, otherwise we need to choose one of them (and it's possible their `f_min` are different).

2022-10-25 13:21 UTC, ahnitz commented on BBHX_PhenomD.py
> +    if 'f_lower' in params and 't_obs_start' not in params:
@WuShichao You may want to check how this behaves in practice. I think f_lower might always be in the dict, but if it is 0 or -1 it should probably be treated as if it weren't.

2022-10-25 13:22 UTC, ahnitz commented on BBHX_PhenomD.py
> +        freq_array = np.logspace(0.0001, 1, num=100)
What if someone sets f_lower and t_obs_start? Should that not also be OK?

2022-10-25 13:24 UTC, WuShichao commented on BBHX_PhenomD.py
> +        freq_array = np.logspace(0.0001, 1, num=100)
@ahnitz In that case, `f_lower` and `t_obs_start` may corresponding to different `f_min`. Maybe it would be better just let users set one of them.

2022-10-25 13:26 UTC, ahnitz commented on BBHX_PhenomD.py
> +        freq_array = np.logspace(0.0001, 1, num=100)
The one caveat here is the case of higher modes, were the frequency start doesn't quite have a unique (different for each mode) same mapping to time, so being able to set both would be useful.

2022-10-25 14:52 UTC, WuShichao commented on BBHX_PhenomD.py
> +        freq_array = np.logspace(0.0001, 1, num=100)
@ahnitz That makes sense. In that case, we must choose the min `f_min` from `f_lower` and `t_obs_start`.

2022-11-08 11:43 UTC, spxiwh commented on BBHX_PhenomD.py
> +@functools.lru_cache()
@WuShichao This can receive variable inputs, but in the case that the inputs are always different (ie. you will never send the same combination of m1, m2 and f_lower), it will not do anything.

*If* you wanted to have a speed improvement from caching you would need to do something like rounding the masses to some power of ten (or fraction thereof).

I think for the chirptime computation (which is very quick anyway), this is unnecessary complication, so don't use lru_cache here.

The call to initialize BBHWaveformFD was not quick, but is much faster than the waveform generation. We were getting a speedup by using lru_cache there, but now the call is complicated by having a different mf_min every time. My initial thought is that we should also remove the lru_cache there as well, and separately we could consider a more complicated caching routine here, if it is needed.

2022-11-08 11:45 UTC, spxiwh commented
@WuShichao Would it be possible to provide a profile graph (https://github.com/jrfonseca/gprof2dot) of generating a waveform with this function after this change, and with the lru_cache calls removed? I do want to understand if this has impacted performance.

2022-12-09 15:12 UTC, spxiwh requested changes
Thanks @WuShichao I think I'm just left with minor implementation comments now. Once those are dealt with, I think this is good to merge! Apologies for the delay with this!!

2022-12-09 15:12 UTC, spxiwh commented on BBHX_PhenomD.py
> +from bbhx.utils.constants import *
I think you're only using `YRSID_SI` here. If so, can you just import that, and not import *

2022-12-09 15:12 UTC, spxiwh commented on BBHX_PhenomD.py
>      from bbhx.utils.transform import LISA_to_SSB
Move the BBHx import to the top to be consistent *or* move the other bbhx import to here.

2022-12-09 15:12 UTC, spxiwh commented on BBHX_PhenomD.py
> +        params.pop('f_lower')
You *must* copy params before doing this. We can't change input structures here in a way that PyCBC may not expect.

2022-12-09 15:12 UTC, spxiwh commented on BBHX_PhenomD.py
> +        params.pop('f_lower')
Do we actually need to do this? Could we not combine this logic into line 68?

`if ('f_lower' not in params) or (params['f_lower'] < 0):`

2022-12-09 15:12 UTC, spxiwh commented on BBHX_PhenomD.py
> +        t_max = chirptime(m1=m1, m2=m2, f_lower=1e-4)
It's hardcoded here that f_lower cannot be smaller than 0.0001 if f_lower is not provided in the params. This might be confusing if you ask for a year-long waveform, but you get something much shorter returned because of this condition.

2022-12-09 15:12 UTC, spxiwh commented on BBHX_PhenomD.py
> +        f_min_input = params['f_lower'] # in Hz
I think if fmin is provided as a parameter, that's the fmin that must be used! Perhaps raise a warning (or even an error) if the fmin results in a waveform that is longer than t_obs_start, but I don't think fmin should be changed here ... And I don't think the 0.0001 number should appear here either.

2022-12-10 12:04 UTC, WuShichao commented on BBHX_PhenomD.py
> +from bbhx.utils.constants import *
Thanks! I change it to `from bbhx.utils.constants import MTSUN_SI, YRSID_SI`.

2022-12-10 12:09 UTC, WuShichao commented on BBHX_PhenomD.py
>      from bbhx.utils.transform import LISA_to_SSB
Now I move all bbhx imports to the top:
```
from bbhx.utils.constants import MTSUN_SI, YRSID_SI
from bbhx.waveformbuild import BBHWaveformFD
from bbhx.utils.transform import LISA_to_SSB
```

2022-12-10 12:32 UTC, WuShichao commented on BBHX_PhenomD.py
> +        params.pop('f_lower')
Now I use `nparams = params.copy()` and `if ('f_lower' not in nparams) or (nparams['f_lower'] < 0):`.

2022-12-10 13:53 UTC, WuShichao commented on BBHX_PhenomD.py
> +        t_max = chirptime(m1=m1, m2=m2, f_lower=1e-4)
0.1mHz is the low-frequency cutoff for LISA. The `f_min` of 1 year-long SMBHB signal is shown here https://lisa-ldc.lal.in2p3.fr/static/data/img/Sangria_FD.png which is above 0.1mHz, so I think it's safe for SMBHB. I think SOBHB's typical `f_min` is at the high-frequency end of LISA, the plot in slack channel is 5-years long GW150914, and its `f_min` is above 0.01Hz. So for 1 year-long input, `f_min` will be calculated from `t_obs_start`.

2022-12-10 14:24 UTC, WuShichao commented on BBHX_PhenomD.py
> +        f_min_input = params['f_lower'] # in Hz
I change this to
```
        if f_min < f_min_tobs:
            err_msg = f"Input 'f_lower' is lower than the value calculated from 't_obs_start'."
```

2022-12-13 14:43 UTC, spxiwh commented on BBHX_PhenomD.py
> +    nparams = params.copy()
As you no longer *change* nparams, the copy is no longer needed, and you can just use `params` directly.

2022-12-13 14:43 UTC, spxiwh commented on BBHX_PhenomD.py
> +        t_max = chirptime(m1=m1, m2=m2, f_lower=1e-4)
Okay, I would rather than 1E-4 not be hardcoded in here, but I do want this merged, so am happy to consider this again later if needed.

2022-12-13 14:44 UTC, spxiwh approved these changes
I made one more minor request, but I think I would then be happy for this to be merged!

2022-12-14 09:45 UTC, spxiwh commented on BBHX_PhenomD.py
> +            err_msg = f"Please set 'f_final' in **params."
Just ran into this: If you get here, you need to `raise` the error message, otherwise this just carries on and fails a bit further down, without saying that we need to set f_final!

2022-12-14 14:23 UTC, WuShichao commented on BBHX_PhenomD.py
> +            err_msg = f"Please set 'f_final' in **params."
@spxiwh Thanks! I have modified my code. Alex is on holiday now, you can merge this if this is good enough.

2022-12-14 14:30 UTC, merged